spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/bookDelivery
  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html


